### ISSUE TITLE
Dateiendungen für jeden Inhalts-Typ 

### ISSUE THREAD

**Issue by twillfade** [nkirschi/Mathbase#36]
Noch mal drüberschauen, ob die Dateiendungen der einzelnen Inhalts-Typen passen

**Comment by lumpenputzer** [comment]
Sollte eigentlich passen. Zwar schränken wir ein, aber die erlaubten Dateien sind in ihren jeweiligen Dateitypen eigentlich immer Kompressionsmäßig am besten sein (Gegenüber zB .GIF ... )
